# Channels format should be like this: ["channel", "channel2", "channel3"] or
# just ["channel"] for a single entry
#
# Set use_config_channels to true to use the channels from the config, or false to
# ask you for channels every time
#
# Highlights are added in the same format as channels, it colors a message in red
# if it contains one of your highlight phrases (a good example is your username)
# you can have [""] for none
#
# Logging enables logging the chat to a text file (true for on, false for off)
#
# log_save_lines is the number of lines before the log file is saved (usually this default is fine, a lower number will
# cause the log to write to disk a lot but will have more lines saved in case of some sort of error or crash, although the
# program will try to save any remaining lines when it is closed)
#
# hide_single_channel to 'true' will hide the channel name if connected to just one channel

[general]
channels = ["change_me"]
use_config_channels = false
highlights = [""]

logging = true
log_save_lines = 5

sub_badge = true
mod_badge = true
hide_single_channel = false

# Available text colors are:
# white black red green yellow blue magenta cyan
#
# 'Highlight' and 'sub colors' are for the message background

[colors]
chat = "white"
highlight = "red"
error = "red"
join = "green"
part = "red"
modstatus = "cyan"
subnotice = "magenta"
